list:
    path:  ''
    defaults:
        _controller: repregid_api.controller.crud:listAction
        filterType: '*'
        filterMethod: GET
        groupSuffix: list
    methods: [GET]

view:
    path:  '/{id}'
    defaults:
        _controller: repregid_api.controller.crud:viewAction
        groupSuffix: detail
        idName: 'id'
    methods: [GET]
    requirements:
        id: '\d+'

create:
    path:  ''
    defaults:
        _controller: repregid_api.controller.crud:createAction
        formType: '*'
        formMethod: POST
        groupSuffix: detail
    methods: [POST]

update:
    path:  '/{id}'
    defaults:
        _controller: repregid_api.controller.crud:updateAction
        formType: '*'
        formMethod: PATCH
        groupSuffix: detail
        idName: 'id'
    methods: [PATCH]
    requirements:
        id: '\d+'

delete:
    path:  '/{id}'
    defaults:
        _controller: repregid_api.controller.crud:deleteAction
        idName: 'id'
    methods: [DELETE]
    requirements:
        id: '\d+'