services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Repregid\ApiBundle\Service\:
        resource: '../../Service/*'
        exclude: '../../Service/DataFilter/ResultProvider.php'

    Repregid\ApiBundle\PostponedCommands\:
        resource: '../../PostponedCommands/*'
        exclude: '../../PostponedCommands/PostponedCommandListener.php'

    Repregid\ApiBundle\DependencyInjection\Configurator: ~
    Repregid\ApiBundle\Routing\ApiLoader:
        tags: ['routing.loader']

    repregid_api.controller.crud:
        class: '%repregid_api.controller.crud.class%'